// Copyright 2026 OfficeCLI (https://OfficeCLI.AI)
// SPDX-License-Identifier: Apache-2.0

namespace OfficeCli.Handlers;

public partial class PowerPointHandler
{
    /// <summary>
    /// Adjust-guide names each preset geometry declares in its ECMA-376
    /// presetShapeDefinitions &lt;avLst&gt;, in declaration order, keyed by the
    /// preset's OOXML name (prstGeom/@prst). Real PowerPoint validates every
    /// authored &lt;a:gd name="…"&gt; against this list and refuses the file
    /// (0x80070570) on a name the preset does not declare — e.g. any guide on
    /// an ellipse (no handles), or "adj1" on a roundRect (its guide is "adj") —
    /// although the OpenXML SDK schema accepts any token. An empty array means
    /// the preset has no adjust handles. Presets absent from the table keep
    /// the pass-through behaviour. Autoshape entries were generated from the
    /// spec's avLst data; the connector/line entries (not autoshapes) were
    /// added by hand from the same presetShapeDefinitions.
    /// </summary>
    private static readonly System.Collections.Generic.IReadOnlyDictionary<string, string[]> PresetAdjustGuideNames =
        new System.Collections.Generic.Dictionary<string, string[]>(System.StringComparer.Ordinal)
    {
        ["accentBorderCallout1"] = new[] { "adj1", "adj2", "adj3", "adj4" },
        ["accentBorderCallout2"] = new[] { "adj1", "adj2", "adj3", "adj4", "adj5", "adj6" },
        ["accentBorderCallout3"] = new[] { "adj1", "adj2", "adj3", "adj4", "adj5", "adj6", "adj7", "adj8" },
        ["accentCallout1"] = new[] { "adj1", "adj2", "adj3", "adj4" },
        ["accentCallout2"] = new[] { "adj1", "adj2", "adj3", "adj4", "adj5", "adj6" },
        ["accentCallout3"] = new[] { "adj1", "adj2", "adj3", "adj4", "adj5", "adj6", "adj7", "adj8" },
        ["actionButtonBackPrevious"] = System.Array.Empty<string>(),
        ["actionButtonBeginning"] = System.Array.Empty<string>(),
        ["actionButtonBlank"] = System.Array.Empty<string>(),
        ["actionButtonDocument"] = System.Array.Empty<string>(),
        ["actionButtonEnd"] = System.Array.Empty<string>(),
        ["actionButtonForwardNext"] = System.Array.Empty<string>(),
        ["actionButtonHelp"] = System.Array.Empty<string>(),
        ["actionButtonHome"] = System.Array.Empty<string>(),
        ["actionButtonInformation"] = System.Array.Empty<string>(),
        ["actionButtonMovie"] = System.Array.Empty<string>(),
        ["actionButtonReturn"] = System.Array.Empty<string>(),
        ["actionButtonSound"] = System.Array.Empty<string>(),
        ["arc"] = new[] { "adj1", "adj2" },
        ["bentArrow"] = new[] { "adj1", "adj2", "adj3", "adj4" },
        ["bentConnector2"] = System.Array.Empty<string>(),
        ["bentConnector3"] = new[] { "adj1" },
        ["bentConnector4"] = new[] { "adj1", "adj2" },
        ["bentConnector5"] = new[] { "adj1", "adj2", "adj3" },
        ["bentUpArrow"] = new[] { "adj1", "adj2", "adj3" },
        ["bevel"] = new[] { "adj" },
        ["blockArc"] = new[] { "adj1", "adj2", "adj3" },
        ["borderCallout1"] = new[] { "adj1", "adj2", "adj3", "adj4" },
        ["borderCallout2"] = new[] { "adj1", "adj2", "adj3", "adj4", "adj5", "adj6" },
        ["borderCallout3"] = new[] { "adj1", "adj2", "adj3", "adj4", "adj5", "adj6", "adj7", "adj8" },
        ["bracePair"] = new[] { "adj" },
        ["bracketPair"] = new[] { "adj" },
        ["callout1"] = new[] { "adj1", "adj2", "adj3", "adj4" },
        ["callout2"] = new[] { "adj1", "adj2", "adj3", "adj4", "adj5", "adj6" },
        ["callout3"] = new[] { "adj1", "adj2", "adj3", "adj4", "adj5", "adj6", "adj7", "adj8" },
        ["can"] = new[] { "adj" },
        ["chartPlus"] = System.Array.Empty<string>(),
        ["chartStar"] = System.Array.Empty<string>(),
        ["chartX"] = System.Array.Empty<string>(),
        ["chevron"] = new[] { "adj" },
        ["chord"] = new[] { "adj1", "adj2" },
        ["circularArrow"] = new[] { "adj1", "adj2", "adj3", "adj4", "adj5" },
        ["cloud"] = System.Array.Empty<string>(),
        ["cloudCallout"] = new[] { "adj1", "adj2" },
        ["corner"] = new[] { "adj1", "adj2" },
        ["cornerTabs"] = System.Array.Empty<string>(),
        ["cube"] = new[] { "adj" },
        ["curvedConnector2"] = System.Array.Empty<string>(),
        ["curvedConnector3"] = new[] { "adj1" },
        ["curvedConnector4"] = new[] { "adj1", "adj2" },
        ["curvedConnector5"] = new[] { "adj1", "adj2", "adj3" },
        ["curvedDownArrow"] = new[] { "adj1", "adj2", "adj3" },
        ["curvedLeftArrow"] = new[] { "adj1", "adj2", "adj3" },
        ["curvedRightArrow"] = new[] { "adj1", "adj2", "adj3" },
        ["curvedUpArrow"] = new[] { "adj1", "adj2", "adj3" },
        ["decagon"] = new[] { "vf" },
        ["diagStripe"] = new[] { "adj" },
        ["diamond"] = System.Array.Empty<string>(),
        ["dodecagon"] = System.Array.Empty<string>(),
        ["donut"] = new[] { "adj" },
        ["doubleWave"] = new[] { "adj1", "adj2" },
        ["downArrow"] = new[] { "adj1", "adj2" },
        ["downArrowCallout"] = new[] { "adj1", "adj2", "adj3", "adj4" },
        ["ellipse"] = System.Array.Empty<string>(),
        ["ellipseRibbon"] = new[] { "adj1", "adj2", "adj3" },
        ["ellipseRibbon2"] = new[] { "adj1", "adj2", "adj3" },
        ["flowChartAlternateProcess"] = System.Array.Empty<string>(),
        ["flowChartCollate"] = System.Array.Empty<string>(),
        ["flowChartConnector"] = System.Array.Empty<string>(),
        ["flowChartDecision"] = System.Array.Empty<string>(),
        ["flowChartDelay"] = System.Array.Empty<string>(),
        ["flowChartDisplay"] = System.Array.Empty<string>(),
        ["flowChartDocument"] = System.Array.Empty<string>(),
        ["flowChartExtract"] = System.Array.Empty<string>(),
        ["flowChartInputOutput"] = System.Array.Empty<string>(),
        ["flowChartInternalStorage"] = System.Array.Empty<string>(),
        ["flowChartMagneticDisk"] = System.Array.Empty<string>(),
        ["flowChartMagneticDrum"] = System.Array.Empty<string>(),
        ["flowChartMagneticTape"] = System.Array.Empty<string>(),
        ["flowChartManualInput"] = System.Array.Empty<string>(),
        ["flowChartManualOperation"] = System.Array.Empty<string>(),
        ["flowChartMerge"] = System.Array.Empty<string>(),
        ["flowChartMultidocument"] = System.Array.Empty<string>(),
        ["flowChartOfflineStorage"] = System.Array.Empty<string>(),
        ["flowChartOffpageConnector"] = System.Array.Empty<string>(),
        ["flowChartOnlineStorage"] = System.Array.Empty<string>(),
        ["flowChartOr"] = System.Array.Empty<string>(),
        ["flowChartPredefinedProcess"] = System.Array.Empty<string>(),
        ["flowChartPreparation"] = System.Array.Empty<string>(),
        ["flowChartProcess"] = System.Array.Empty<string>(),
        ["flowChartPunchedCard"] = System.Array.Empty<string>(),
        ["flowChartPunchedTape"] = System.Array.Empty<string>(),
        ["flowChartSort"] = System.Array.Empty<string>(),
        ["flowChartSummingJunction"] = System.Array.Empty<string>(),
        ["flowChartTerminator"] = System.Array.Empty<string>(),
        ["foldedCorner"] = System.Array.Empty<string>(),
        ["frame"] = new[] { "adj1" },
        ["funnel"] = System.Array.Empty<string>(),
        ["gear6"] = new[] { "adj1", "adj2" },
        ["gear9"] = new[] { "adj1", "adj2" },
        ["halfFrame"] = new[] { "adj1", "adj2" },
        ["heart"] = System.Array.Empty<string>(),
        ["heptagon"] = new[] { "hf", "vf" },
        ["hexagon"] = new[] { "adj", "vf" },
        ["homePlate"] = new[] { "adj" },
        ["horizontalScroll"] = new[] { "adj" },
        ["irregularSeal1"] = System.Array.Empty<string>(),
        ["irregularSeal2"] = System.Array.Empty<string>(),
        ["leftArrow"] = new[] { "adj1", "adj2" },
        ["leftArrowCallout"] = new[] { "adj1", "adj2", "adj3", "adj4" },
        ["leftBrace"] = new[] { "adj1", "adj2" },
        ["leftBracket"] = new[] { "adj" },
        ["leftCircularArrow"] = new[] { "adj1", "adj2", "adj3", "adj4", "adj5" },
        ["leftRightArrow"] = new[] { "adj1", "adj2" },
        ["leftRightArrowCallout"] = new[] { "adj1", "adj2", "adj3", "adj4" },
        ["leftRightCircularArrow"] = new[] { "adj1", "adj2", "adj3", "adj4", "adj5" },
        ["leftRightRibbon"] = new[] { "adj1", "adj2", "adj3" },
        ["leftRightUpArrow"] = new[] { "adj1", "adj2", "adj3" },
        ["leftUpArrow"] = new[] { "adj1", "adj2", "adj3" },
        ["lightningBolt"] = System.Array.Empty<string>(),
        ["line"] = System.Array.Empty<string>(),
        ["lineInv"] = System.Array.Empty<string>(),
        ["mathDivide"] = new[] { "adj1", "adj2", "adj3" },
        ["mathEqual"] = new[] { "adj1", "adj2" },
        ["mathMinus"] = new[] { "adj1" },
        ["mathMultiply"] = new[] { "adj1" },
        ["mathNotEqual"] = new[] { "adj1", "adj2", "adj3" },
        ["mathPlus"] = new[] { "adj1" },
        ["moon"] = new[] { "adj" },
        ["nonIsoscelesTrapezoid"] = new[] { "adj1", "adj2" },
        ["noSmoking"] = new[] { "adj" },
        ["notchedRightArrow"] = new[] { "adj1", "adj2" },
        ["octagon"] = new[] { "adj" },
        ["parallelogram"] = new[] { "adj" },
        ["pentagon"] = new[] { "hf", "vf" },
        ["pie"] = new[] { "adj1", "adj2" },
        ["pieWedge"] = System.Array.Empty<string>(),
        ["plaque"] = new[] { "adj" },
        ["plaqueTabs"] = System.Array.Empty<string>(),
        ["plus"] = new[] { "adj" },
        ["quadArrow"] = new[] { "adj1", "adj2", "adj3" },
        ["quadArrowCallout"] = new[] { "adj1", "adj2", "adj3", "adj4" },
        ["rect"] = System.Array.Empty<string>(),
        ["ribbon"] = new[] { "adj1", "adj2" },
        ["ribbon2"] = new[] { "adj1", "adj2" },
        ["rightArrow"] = new[] { "adj1", "adj2" },
        ["rightArrowCallout"] = new[] { "adj1", "adj2", "adj3", "adj4" },
        ["rightBrace"] = new[] { "adj1", "adj2" },
        ["rightBracket"] = new[] { "adj" },
        ["round1Rect"] = new[] { "adj" },
        ["round2DiagRect"] = new[] { "adj1", "adj2" },
        ["round2SameRect"] = new[] { "adj1", "adj2" },
        ["roundRect"] = new[] { "adj" },
        ["rtTriangle"] = System.Array.Empty<string>(),
        ["smileyFace"] = new[] { "adj" },
        ["snip1Rect"] = new[] { "adj" },
        ["snip2DiagRect"] = new[] { "adj1", "adj2" },
        ["snip2SameRect"] = new[] { "adj1", "adj2" },
        ["snipRoundRect"] = new[] { "adj1", "adj2" },
        ["squareTabs"] = System.Array.Empty<string>(),
        ["star10"] = new[] { "adj", "hf" },
        ["star12"] = new[] { "adj" },
        ["star16"] = new[] { "adj" },
        ["star24"] = new[] { "adj" },
        ["star32"] = new[] { "adj" },
        ["star4"] = new[] { "adj" },
        ["star5"] = new[] { "adj", "hf", "vf" },
        ["star6"] = new[] { "adj", "hf" },
        ["star7"] = new[] { "adj", "hf", "vf" },
        ["star8"] = new[] { "adj" },
        ["straightConnector1"] = System.Array.Empty<string>(),
        ["stripedRightArrow"] = new[] { "adj1", "adj2" },
        ["sun"] = new[] { "adj" },
        ["swooshArrow"] = new[] { "adj1", "adj2" },
        ["teardrop"] = new[] { "adj" },
        ["trapezoid"] = new[] { "adj" },
        ["triangle"] = new[] { "adj" },
        ["upArrow"] = new[] { "adj1", "adj2" },
        ["upArrowCallout"] = new[] { "adj1", "adj2", "adj3", "adj4" },
        ["upDownArrow"] = new[] { "adj1", "adj1", "adj2", "adj2" },
        ["upDownArrowCallout"] = new[] { "adj1", "adj2", "adj3", "adj4" },
        ["uturnArrow"] = new[] { "adj1", "adj2", "adj3", "adj4", "adj5" },
        ["verticalScroll"] = new[] { "adj" },
        ["wave"] = new[] { "adj1", "adj2" },
        ["wedgeEllipseCallout"] = new[] { "adj1", "adj2" },
        ["wedgeRectCallout"] = new[] { "adj1", "adj2" },
        ["wedgeRoundRectCallout"] = new[] { "adj1", "adj2", "adj3" },
    };
}
